### ISSUE TITLE
Android `googleSilentSignIn` in 5.2.0/5.2.1

### ISSUE THREAD

**Issue by jamesgroat** [inouiw/capacitor-native-google-one-tap-signin#19]
This function here:

https://github.com/inouiw/capacitor-native-google-one-tap-signin/blob/main/android/src/main/java/com/proventask/capacitor/GoogleOneTapAuth/GoogleOneTapAuth.java#L255

Is not found in the file inside the published versions 5.2.0 and 5.2.1 but is found in 5.1.10.

When I try building my Android build using 5.2.1 I get:

`cannot find symbol method googleSilentSignIn(PluginCall)`

**Comment by inouiw** [comment]
Hi @jamesgroat,
can you upgrade to version 6.0.0?
Version 6.0.0 uses capacitor 6 and GoogleOneTapAuth was migrated to Kotlin. See https://github.com/inouiw/capacitor-native-google-one-tap-signin/issues/17#issuecomment-2148366467

**Comment by jamesgroat** [comment]
@inouiw I get this error now:

`Plugin with id 'org.jetbrains.kotlin.android' not found.`

**Comment by inouiw** [comment]
@jamesgroat I have created a fix and published a new version: 6.0.2
Please tell me if it works now.

**Comment by jamesgroat** [comment]
@inouiw that worked -- thanks!
